sudo: required
language: node_js
notifications:
  email: joaovitorteixeira10.jvt@gmail.com
node_js:
  - 12.13.1
services:
  - postgresql
  - redis-server
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
before_script:
  - psql -c 'create database etanois_test;' -U postgres
  - npm i -g sequelize-cli gulp-cli
  - npm install
  - gulp
script:
  - npm run unit-test