version: '3'

services:
  postgres:
    container_name: postgres-etanois
    image: postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=etanois
    volumes:
      - "postgres-data:/data/postgres"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks: 
      - etanois-network
  
  pgadmin:
    container_name: pgadmin-etanois
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    networks:
      - etanois-network
  
  redis:
    container_name: redis-etanois
    image: redis
    ports:
      - "6379:6379"

  app:
    container_name: app-etanois-backend
    build: .
    ports:
      - "80:3000"
    command: npm run production
    networks:
      - etanois-network

networks: 
  etanois-network:
    driver: bridge

volumes: 
  postgres-data: